data_root: ./chest_xray
metadata_output_path: ./outputs/metadata/metadata.csv
analysis_output_dir: ./outputs/data_analysis
preprocessed_output_root: ./outputs/preprocessed/chest_xray_grayscale
preprocessed_metadata_output_path: ./outputs/preprocessed/preprocessed_metadata.csv

preprocessing:
  grayscale: true
  resize:
    enabled: true
    size: [64, 64]

logistic_regression:
  output_dir: ./outputs/logistic_regression
  experiment_name: logistic_regression
  max_iter: 5000
  class_weight: balanced
  pca_n_components: 0.85
  random_state: 42
  solver: lbfgs
